sudo: required
services:
  - docker

before_install:
  - docker build -t ksganesh/docker-react -f Dockerfile.dev .

script:
  - docker run ksganesh/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region:  "ap-south-1"
  app: "React"
  env: "React-env"
  bucket_name: "elasticbeanstalk-ap-south-1-899884035939"
  bucket_path: "React"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"


